import { notFound } from "next/navigation";

const articles = [
      { 
        slug: "behbudi-global-tafakkuri", 
        title: "MAHMUDXO‘JA BEHBUDIYNING GLOBAL TAFAKKURI: TARIXIY TAJRIBA VA BUGUNGI SABOQLAR", 
        author: "A’zamjon DADAXONOV", 
        page: "12-16", 
        date: "19.01.2026", 
        doi: "https://doi.org/10.5281/zenodo.19031757",
        abstract: "Ushbu maqolada jadidchilik harakatining yetakchi namoyandalaridan biri Mahmudxo‘ja Behbudiyning xalqaro dunyoqarashi, xususan, uning G‘arb sivilizatsiyasi, Yevropa taraqqiyoti, ilm-fan va modern jamiyat haqidagi qarashlari ilmiy-tahliliy jihatdan o‘rganiladi. Behbudiy publitsistikasi, dramaturgiyasi va ma’rifiy faoliyati misolida uning G‘arbni ko‘r-ko‘rona taqlid qilish emas, balki tanqidiy o‘zlashtirish tarafdori bo‘lganligi asoslab beriladi. Maqolada Behbudiy qarashlarining tarixiy ildizlari, jadidchilik kontekstidagi o‘rni hamda bugungi globallashuv sharoitidagi dolzarbligi yoritiladi.",
        file: "/1.pdf",
        keywords: "Mahmudxo‘ja Behbudiy, jadidchilik, xalqaro dunyoqarash, G‘arb sivilizatsiyasi, modernizatsiya, matbuot, ta’lim islohoti."},
      { 
        slug: "mahmudxoja-behbudiy-ijodi-va-faoliyatida-turkiy-xalqlarning-ozodligi-hamda-birlashuviga-bolgan-etibor",
        title: `MАHMUDXO‘JА BEHBUDIY IJODI VА FАOLIYATIDА TURKIY XАLQLАRNING OZODLIGI HАMDА BIRLАSHUVIGА BO‘LGАN E’TIBOR`, 
        author: "Barchinoy JO‘RAEVA", 
        page: "12-16", 
        date: "19.01.2026", 
        doi: "https://doi.org/10.5281/zenodo.19031806",
        abstract: "Ushbu maqolada jadidchilik harakatining yirik namoyondasi Mahmudxo‘ja Behbudiy ijodida Turkiston xalqlariining ozodligi gʼoyasi ilmiy-nazariy jihatdan tadqiq etilgan. Behbudiyning publitsistik, dramatik va maʼrifiy asarlari misolida millat, til, din va maʼrifat masalalaridagi qarashlarini tahlil qilib o‘tadi. Shu bilan birga Behbudiy faoliyatini o‘rgangan zamonaviy olimlarning ilmiy xulosalariga tayanilgan holda uning turkiy xalqlarning maʼnaviy uygʼonishidagi o‘rni ochib beriladi.",
        file: "/2.pdf", 
        keywords: "Behbudiy, jadidchilik, turkiy xalqlar, milliy birlik, maʼrifat, matbuot, mafkura."},
      { 
        slug: "mahmudxoja-behbudiy-maqolalarida-ijtimoiy-siyosiy-muammolarning-aks-etishi",
        title: "MAHMUDXO‘JA BEHBUDIY MAQOLALARIDA IJTIMOIY-SIYOSIY MUAMMOLARNING AKS ETISHI", 
        author: "Sitora SHOKIROVA & Diyorbek TURAYEV", 
        page: "12-16", 
        date: "19.01.2026", 
        doi: "https://doi.org/10.5281/zenodo.19031832",
        abstract: "Ushbu maqola Mahmudxo‘ja Behbudiyning publitsistik merosida yoritilgan o‘lkadagi ijtimoiy-siyosiy muammolarning aks etishi tahlil qilinadi. Tadqiqot davomida Behbudiyning maqolalarida XIX asr oxiri XX asr boshlarida Turkiston jamiyatining siyosiy elitasi ichida shakllangan ikki qarama-qarshi g‘oyalar kurashi davridagi siyosiy holatlar, u yerdagi xalqning ma’naviy jihatdan muammolari va ijtimoiy sustkashligi qiyosiy tahlil qilinadi. Maqolada Behbudiy publitsistikasida jamiyatni modernizatsiya qilishga qaratilgan konseptual dastur sifatida baholanadi va uning g‘oyalari bugungi ijtimoiy-siyosiy jarayonlar bilan uzviy bog‘liq ekanligi yoritib beriladi.",
        file: "/3.pdf", 
        keywords: "Mahmudxo‘ja Behbudiy, jadidchilik, publitsistika, ijtimoiy-siyosiy tafakkur, ma’rifatparvarlik, madaniy modernizatsiya, milliy ong."},
      { 
        slug: "mahmudxoja-behbudiyning-publitsistik-merosi-va-uning-bugungi-ahamiyati",
        title: "MAHMUDXOʻJA BEHBUDIYNING PUBLITSISTIK MEROSI VA UNING BUGUNGI AHAMIYATI", 
        author: "Gulhayo AKRAMOVA", 
        page: "29-30", 
        date: "19.01.2026", 
        doi: "https://doi.org/10.5281/zenodo.19031868",
        abstract: "XX asrda Markaziy Osiyo SSSRning maʼnaviy va iqtisodiy jihatdan bosimi ostida yashayotganda, ilmiy va madaniy sohalardan qatʼiyan cheklanganda, hamma ham jim qolmadi. Ulardan biri Mahmudxoʻja Behbudiy boʻlib, oʻzbek publitsistikasining asoschilaridan biridir.",
        file: "/4.pdf", 
        keywords: "Publistik maqolalar, jurnalistika, matbuot, jurnal, gazeta, dramaturgiya, ilm-fan, yangicha fikrlash."},
      { 
        slug: "behbudiy-ijodida-teatr-sanati",
        title: "BEHBUDIY IJODIDA TEATR SAN’ATI", 
        author: "Izzatilla ZOHIDJONOV", 
        page: "31-33", 
        date: "19.01.2026", 
        doi: "https://doi.org/10.5281/zenodo.19031895",
        abstract: `Ushbu maqolada jadidchilik harakatining yetakchisi Mahmudxo‘ja Behbudiyning o‘zbek teatr san’ati rivojiga qo‘shgan hissasi, xususan, "Padarkush" dramasi misolida tahlil qilinadi. Muallif Behbudiyning teatrga "ibratxona" va axloq maktabi sifatida bergan ta’riflarini bayon etadi. Shuningdek, maqolada "Padarkush" dramasidagi obrazlar tizimi, ularning ismlari zamiridagi ramziy ma’nolar va asarning jamiyatni uyg‘otishdagi ahamiyati amerikalik olim Eduard Allvord hamda o‘zbek adibi Abdulla Qodiriy fikrlari asosida yoritib berilgan.`,
        file: "/5.pdf", 
        keywords: `Behbudiy, jadidchilik, teatr, "Padarkush", ibratxona, drama, ma’rifatparvarlik, obrazlar tizimi, "Kolizey", Turkiston matbuoti.`},
      {
        slug: "mahmudxoja-behbudiy-publisistikasida-tanqid-va-ijtimoiy-illatlar-masalasi", 
        title: "MAHMUDXO‘JA BEHBUDIY PUBLISISTIKASIDA TANQID VA IJTIMOIY ILLATLAR MASALASI", 
        author: "Mashhura JO‘RAQULOVA", 
        page: "34-36", 
        date: "19.01.2026", 
        doi: "https://doi.org/10.5281/zenodo.19031917",
        abstract: `Ushbu maqolada ma’rifatparvar yozuvchi Mahmudxo‘ja Behbudiyning “Bizni kemirguvchi illatlar” va “Tanqid – saralamoqdur” nomli publisistik maqolalari tahlil qilanadi. Mazkur maqolalar orqali Behbudiy tanqidning nazariy asoslarini amaliy misollar – to‘y va aza marosimlari misolida ko’rsatib, tanqidning bosh maqsadi jamiyat tafakkurini isloh qilishga qaratganligining guvohi bo’lamiz.`,
        file: "/6.pdf", 
        keywords: "tanqid, ma’rifatparvarlik, munaqqid, illat, isloh, to‘y va aza marosimlari, isrofgarchilik, obro‘."},
      { 
        slug: "mahmudxoja-behbudiy-publitsistikasidagi-dolzarblik-masalalari",
        title: "MAHMUDXO‘JA BEHBUDIY PUBLITSISTIKASIDAGI DOLZARBLIK MASALALARI", 
        author: "Timur USUPOV & Shahribonu TURIKOVA", 
        page: "37-41", 
        date: "19.01.2026", 
        doi: "https://doi.org/10.5281/zenodo.19031984",
        abstract: `Mahmudxo‘ja Behbudiy publitsistikasi – nafaqat jadidlik harakatining mafkuraviy asosi balki jamiyat hayotida, siyosat sahnasida, o‘zbek milliy jurnalistikasining shakillanishida muhim o‘rin egallaydi. Ushbu maqolada Mahmudxoja Behbudiyning publitsistik merosining bugungi kundagi dolzarbligi jurnalistika rivojidagi o‘rni, talimda va jamiyatdagi hissasi ustida fikir yuritildi. “Ikki emas to‘rt til kerak”, “Bizni kemiruvchi illatlar” va “Padarkush” dramasi tahlil qilinadi.`,
        file: "/7.pdf", 
        keywords: "Mahmudxo‘ja Behbudiy, publitsistika, jamiyat,jadidlik, ta’lim, taraqqiyot, millat ongi."},
      { 
        slug: "turkiston-jadidlik-harakati-asoschisi",
        title: "TURKISTON JADIDLIK HARAKATI ASOSCHISI", 
        author: "Dilnavoz RIZAYEVA", 
        page: "42-45", 
        date: "19.01.2026", 
        doi: "https://doi.org/10.5281/zenodo.19031944",
        abstract: `Ushbu maqolada Mahmudxo‘ja Behbudiyning ta’lim sohasidagi faoliyati, jadid maktablarini tashkil etishi, matbaa va nashriyot faoliyati haqida fikr bildiriladi. Shuningdek, til va adabiyot rivojiga qo‘shgan hissasi ochib berilgan. Maqolada Mahmudxo‘ja Behbudiyning milliy ongni shakllantirish, madaniy rivojlanish va jamiyat taraqqiyotiga ko‘rsatgan ta’siri o‘rganiladi. Behbudiy g‘oyalarining bugungi kun uchun ahamiyati, ta’lim sohasidagi islohotlari alohida ta’kidlangan.`,
        file: "/8.pdf", 
        keywords: "Mahmudxo‘ja Behbudiy, jadid maktablari, matbaa faoliyati, milliy ta’lim, o‘zbek adabiyoti, jadidchilik harakati, milliy ong, milliy mafkura, jamiyat."},
      { 
        slug: "sovet-axborot-siyosati-va-matbuoti-prinsiplari",
        title: "SOVET AXBOROT SIYOSATI VA MATBUOTI PRINSIPLARI", 
        author: "Nilufar NAMAZOVA", 
        page: "46-49", 
        date: "19.01.2026", 
        doi: "https://doi.org/10.5281/zenodo.19032027",
        abstract: `Maqolada Turkistonda sho‘ro hokimiyati o‘rnatilgandan keyin matbuotning mafkuraviy tizimga bo‘ysundirilishi tahlil qilinadi. Sovet matbuotining sinfiylik, ommaviylik va partiyaviylik prinsiplari asosida uning mustaqil axborot vositasidan partiya siyosati quroliga aylanishi ochib beriladi. Dastlab jadid matbuoti anʼanalari saqlangan bo‘lsa-da, keyinchalik tanqidiy fikr to‘liq cheklangani asoslanadi.`,
        file: "/9.pdf", 
        keywords: "sho‘ro matbuoti, axborot siyosati, sinfiylik, ommaviylik, partiyaviylik, mafkura."},
      { 
        slug: "ozbek-va-tatar-adabiy-aloqalari-behbudiy-va-tatar-ijodkorlari-misolida",
        title: `O‘ZBEK VA TATAR ADABIY ALOQALARI (BEHBUDIY VA TATAR IJODKORLARI MISOLIDA)`, 
        author: "Gulzoda SOATOVA", 
        page: "50-59",
        date: "19.01.2026", 
        doi: "https://doi.org/10.5281/zenodo.19032051",
        abstract: `Maqolada o‘zbek va tatar xalqlarining milliy uyg‘onish davridagi adabiy aloqalari haqida so‘z boradi. Yerli xalq va Rusiya musulmonlari hisoblanmish tatarlar o‘rtasidagi munosabat yoritiladi. Adabiy aloqalar rivojida muhim o‘rin egallagan Behbudiyning tatar ijodkorlari bilan ijodiy aloqasi tahlil etiladi hamda Behbudiy, Ismoil Gaspirali, Zaki Validiy va o‘zbek-tatar xalqlarining sayohatnoma asarlari ustida fikr bildiriladi. Shuningdek, maqolada Behbudiy ijodini o‘rgangan olimlar sanab o‘tiladi. Ijodkor ijodiy merosining gultoji bo‘lmish “Padarkush” asarining sahnalashtirilishida o‘zbek-tatar ijodkorlarining say harakatlari haqidagi ma’lumotlar keltiriladi.`,
        file: "/10.pdf", 
        keywords: "o‘zbek, tatar, adabiy aloqalar, Behbudiy, nasriy sayohatnoma."},
      { 
        slug: "abdulla-qodiriy-publisistikasida-ijtimoiy-masalalarning-yoritilishi",
        title: "ABDULLA QODIRIY PUBLISISTIKASIDA IJTIMOIY MASALALARNING YORITILISHI", 
        author: "Oydin TURDIYEVA & Jahongir TURDIYEV", 
        page: "60-64", 
        date: "19.01.2026", 
        doi: "https://doi.org/10.5281/zenodo.19032075",
        abstract: `Ushbu maqolada Abdulla Qodiriyning 1927-1933 yillarda “Qizil O‘zbekiston” gazetasida chop etilgan turli ijtimoiy masalalarga bag‘ishlangan “Ravot qashqirlari”, “Ma’rifiy ishlarga e’tibor”, “Eski kitoblar savdosiga egalik qilaylik” nomli uchta maqolasi tahlili omma e’tiboriga havola etiladi. Ma’lumki, bu davrlarda matbuot va davriy nashrlar ziyolilar uchun o‘z fikr va mulohazalarini bildiradigan birinchi minbar bo‘lib xizmat qildi. O‘zbek adabiyotida roman janrining asoschisi, shoir, dramaturg va tarjimon Abdulla Qodiriy dolzarb va muhim ijtimoiy masalalarni yoritishi bilan jurnalistikada alohida o‘rin tutdi. Muallif ijodiy merosining katta qismini uning ijtimoiy-madaniy masalalardagi pozitsiyasini aks ettiruvchi jamoat ishlari tashkil etdi. Qodiriyning nashriyot faoliyati ham o‘z davrining tarixiy hujjatidir.`,
        file: "/11.pdf", 
        keywords: "Abdulla Qodiriy, Culkunboy, “Qizil O‘zbekiston”, adabiy-badiiy tashkilotlar, “Ravot qashqirlari”, antiqa kitoblar savdosi."},
      { 
        slug: "xx-asr-ozbek-ayollar-adabiyoti-oydin-sobirova-va-uning-ijodiy-merosi",
        title: "XX ASR O‘ZBEK AYOLLAR ADABIYOTI: OYDIN SOBIROVA VA UNING IJODIY MEROSI", 
        author: "Shaxlo BAZAROVA", 
        page: "65-69", 
        date: "19.01.2026", 
        doi: "https://doi.org/10.5281/zenodo.19032092",
        abstract: `Mazkur maqolada XX asr o‘zbek ayollar adabiyotining yetuk namoyandalaridan biri Oydin Sobirova ijodiy merosi, xususan, uning hikoyalari poetik xususiyatlari tahlil etiladi. Adibaning asarlarida ayol obrazi davr ijtimoiy-siyosiy muhitini aks ettiruvchi asosiy badiiy vosita sifatida talqin qilinadi. Hikoyalarda ayol qismati, ruhiy kechinmalari, ilmma’rifatga intilishi va ijtimoiy faolligi davr ruhi bilan uzviy bog‘liqlikda yoritilgan.`,
        file: "/12.pdf", 
        keywords: "ayollar nasri, hikoya janri, davr ruhi, ayol obrazi, qismat, badiiy detal, poetika, ijtimoiy ong."},
      { 
        slug: "samarqand-jadidchilik-maktabining-asoschisi-akademik-said-rizo-alizodaning-hayot-yoli",
        title: "SAMARQAND JADIDCHILIK MAKTABINING ASOSCHISI AKADEMIK SAID RIZO ALIZODANING HAYOT YO’LI", 
        author: "Mirzoulug’bek YUSUPOV", 
        page: "70-72", 
        date: "19.01.2026", 
        doi: "https://doi.org/10.5281/zenodo.19032114",
        abstract: `Qadim va hamisha navqiron, ko’hna Samarqand zamirida dunyoga kelgan fidoyi jadidlar millat fidoyisi Said Rizo Alizoda ijodi va faoliyati. Vatanimiz ozodligi yo’lida jonini fido qilgan, nogoh istiroblar chekib, tuxmat va soxta ayblovlar ostida qolib, o’z sevgan kasbini, vatani, xalqnidan judo bo’lib, umrining oxirgi kunlarini qamoqxonada o’tkazib, qiynoqlarga chiday olmay dunyodan ko’z yumgan.`,
        file: "/13.pdf", 
        keywords: "Fidoyi jadid, 14 ta tilni bilgan, vatan ozodligi, millat, soxta ayblov, azob uqubatlar."},
      { 
        slug: "fitratning-sharq-siyosati-risolasida-xx-asr-dunyo-siyosiy-manzarasi-tahlili",
        title: "FITRATNING “SHARQ SIYOSATI” RISOLASIDA XX ASR DUNYO SIYOSIY MANZARASI TAHLILI", 
        author: "Shohruxbek OLIMOV", 
        page: "73-79", 
        date: "19.01.2026", 
        doi: "https://doi.org/10.5281/zenodo.19032141",
        abstract: `XX asrning zabardast qalamkashi, adib Abdurauf Fitrat qisqa hayoti davomida 200 dan ortiq katta-kichik asar yozdi. O’z davrining turli nashrlarida publitsistik maqolalar chop etdi. Keyinchalik ana shu maqolalarini to’ldirilgan holda risola sifatida nashr qildirdi. Fitratning 1919 yilda nashr qilingan “Sharq siyosati” risolasi ham “Ishtirokiyun” gazetasida bir necha qismli maqola sifatida nashr qilinib, keyin mustaqil kitob bo’lib chiqqan. “Sharq siyosati” XX asrning boshida dunyodagi geosiyosiy holat, dunyoning katta qismiga egalik qilayotgan davlatlarning dunyo boyliklari uchun kurashi va bu holatda sharqning ahvoli tahlil qilingan. Asar o’zbek publitsistikasining dastlabki geosiyosiy analitik materiali sifatida alohida e’tiborga loyiq.`,
        file: "/14.pdf", 
        keywords: "Fitrat, jadidchilik, ishtirokiyun, jadid matbuoti, sharq va g’arb tafovuti, XX asr tarixi"},
      { 
        slug: "jadidlar-nigohida-oila-va-ayol-fitrat-qarashlari-misolida",
        title: "JADIDLAR NIGOHIDA OILA VA AYOL: FITRAT QARASHLARI MISOLIDA", 
        author: "Nigora ELMURODOVA", 
        page: "80-84", 
        date: "19.01.2026", 
        doi: "https://doi.org/10.5281/zenodo.19032169",
        abstract: `Mazkur tezisda jadidlar dunyoqarashida aks etgan oila va ayol masalasi Fitratning “Oila yoki oilani boshqarish tartiblari” asari misolida tahlil etilgan. Asarda ayolning jamiyatdagi o‘rni, oilaviy tarbiya va ma’naviy mas’uliyatiga doir ilg‘or g‘oyalar yoritilgan. Tadqiqotda Fitrat qarashlari jadidchilik mafkurasi va bugungi gender siyosatining uyg‘unligi nuqtayi nazaridan ko‘rib chiqilgan.`,
        file: "/15.pdf", 
        keywords: "Fitrat, jadidchilik, ayol, oila, ma’rifat, ijtimoiy islohot, gender siyosat."},
      { 
        slug: "rauf-muzaffarzoda-publitsistikasida-marifat-va-taraqqiyot-masalalari",
        title: "RAUF MUZAFFARZODA PUBLITSISTIKASIDA MA’RIFAT VA TARAQQIYOT MASALALARI", 
        author: "Ozoda YUSUPOVA", 
        page: "85-87", 
        date: "19.01.2026", 
        doi: "https://doi.org/10.5281/zenodo.19032202",
        abstract: `Rauf Muzaffarzodaning faoliyati, ilmiy merosini o‘rganish jadid matbuotining ochilmagan qirralarini yoritishda katta ahamiyat kasb etadi. Mazkur maqola doirasida biz Rauf Muzaffarzodaning "Sadoyi Turkiston" gazetasida nashr qilingan milliy matbuot, madaniyat va ma’rifat taraqqiyotiga oid qarashlarini tahlil qilishga harakat qilamiz.`,
        file: "/16.pdf", 
        keywords: "milliy matbuot, jarida, majalla, millat, ta’lim, tarbiya, ma’rifat."},
      { 
        slug: "said-rizo-alizodaning-turkiston-jadidchiligiga-qoshgan-hissasi",
        title: "SAID RIZO ALIZODANING TURKISTON JADIDCHILIGIGA QO‘SHGAN HISSASI", 
        author: "Yunus Safarov", 
        page: "88-90", 
        date: "19.01.2026", 
        doi: "https://doi.org/10.5281/zenodo.19032240",
        abstract: `Ushbu maqolada yaqin tariximizda bo‘lgan voqealarni bevosita tahlil qilishga harakat qilingan.`,
        file: "/17.pdf", 
        keywords: "Mirmaxsum Alizoda, maktab, madrasa, islohot, O‘gutchi, qizil matbuot, jadidchilik."},
      { 
                slug: "abdulla-qodiriy-publististikasining-til-va-uslubiy-xususiyatlari",
                title: "ABDULLA QODIRIY PUBLISTISTIKASINING TIL VA USLUBIY XUSUSIYATLARI", 
                author: "Nazokatxon ISOQOVA", 
                page: "91-94", 
                date: "19.01.2026", 
                doi: "Ushbu maqolada o‘zbek jadid publitsistikasining yirik namoyandasi Abdulla Qodiriyning publitsistik merosi lingvistik va uslubiy jihatdan tahlil qilinadi. Adib publitsistik asarlarida qo‘llangan leksik birliklar, frazeologik vositalar hamda sintaktik qurilmalar ijtimoiy tanqid va ma’rifiy g‘oyalarni ifodalashda muhim ahamiyat kasb etadi.",
                abstract: "https://doi.org/10.5281/zenodo.19032269",
                file: "/18.pdf", 
                keywords: "publitsistika, jadid adabiyoti, uslub, baholovchi leksika, frazeologiya."},
            { 
                slug: "sayid-rizo-alizoda-publitsistikasi",
                title: "SAYID RIZO ALIZODA PUBLITSISTIKASI", 
                author: "Dilorom JONIXONOVA", 
                page: "95-103", 
                date: "19.01.2026", 
                doi: "https://doi.org/10.5281/zenodo.19032583",
                abstract: `Ushbu maqolada Sayid Rizo Alizodaning jurnalistik merosi o'rganiladi, uning ijtimoiysiyosiy qarashlari, ta'lim falsafasi va jadidchilik harakati tarafdori sifatidagi jurnalistik uslubining o'ziga xos unsurlari tahlil qilinadi. Maqolada Alizodaning matbuot orqali jamiyat uyg'onishiga qo'shgan hissasi, aholini ilmiy izlanishlar va ma'rifatga undash, shu bilan birga milliy ong va ijtimoiy mas'uliyatni rivojlantirishga qaratilganligi yoritib beriladi. Uning jurnalistik nutqida davr muammolari, jadid matbuotiga qo'shgan hissasi va uning badiiy va jurnalistik tafakkurini shakllantirgan ta'sirlar chuqur o'rganiladi. Tadqiqot natijalari shuni ko'rsatadiki, Sayid Rizo Alizodaning jurnalistikasi o'zbek matbuoti tarixida muhim bosqichni ifodalaydi.`,
                file: "/19.pdf", 
                keywords: "Sayid Rizo Alizoda, jadidchilik, publitsistika, ma’rifatparvarlik, jadid matbuoti, ijtimoiy fikr, milliy uyg‘onish, Samarqand jadidlari, matbuot tarixi."},
            { 
                slug: "fitratning-hind-sayyohining-qissasi-risolasida-ijtimoiy-masalalar",
                title: "FITRATNING “HIND SAYYOHINING QISSASI” RISOLASIDA IJTIMOIY MASALALAR", 
                author: "Robiya NURIDDINBEKOVA", 
                page: "104-06", 
                date: "19.01.2026", 
                doi: "https://doi.org/10.5281/zenodo.19032601",
                abstract: `Ushbu maqolada Abdurauf Fitratning publisistik faoliyati, xususan adibning “Hind sayyohining qissasi” publisistik risolasidagi ijtimoiy masalalar tahlil qilinadi. Unda risola ijtimoiy uyg‘otuvchi, tanqidiy va ma’rifiy asar sifatida yoritiladi. Shuningdek, maqolada Turkiston jamiyatining savodsizligi, jamiyatdagi boshqa turlituman illatlar fosh etilishi ochib beriladi.`,
                file: "/20.pdf", 
                keywords: "Abdurauf Fitrat, “Hind sayyohining qissasi”, satirik uslub, qoloqlik, savodsizlik, ijtimoiy adolatsizlik, mustamlakachilik."},
            { 
                slug: "dabiy-til-meyorlarining-jadid-matbuoti-va-bugungi-ijtimoiy-tarmoqlardagi-ahamiyati",
                title: "DABIY TIL ME’YORLARINING JADID MATBUOTI VA BUGUNGI IJTIMOIY TARMOQLARDAGI AHAMIYATI", 
                author: "Gulzoda OLIMJANOVA", 
                page: "107-110", 
                date: "19.01.2026", 
                doi: "https://doi.org/10.5281/zenodo.19032605",
                abstract: `Hozirgi kunda O‘zbekiston Respublikasida amalga oshirilayotgan keng ko‘lamli islohotlar hamda milliy taraqqiyot strategiyasida davlat tilining nufuzi va adabiy til me’yorlariga rioya etish masalasi ustuvor vazifalardan biri sifatida belgilangan. Ushbu maqolada adabiy til me’yorlarining shakllanishi va rivojlanishida jadid matbuotining tarixiy o‘rni hamda bugungi ijtimoiy tarmoqlarda ushbu me’yorlarning qo‘llanish holati ilmiy-nazariy va amaliy jihatdan tahlil qilinadi. Jadid matbuoti materiallari asosida o‘zbek adabiy tilining leksik, grammatik va uslubiy me’yorlari mustahkamlanganligi yoritiladi. Bundan tashqari, zamonaviy ijtimoiy tarmoqlarda til me’yorlariga amal qilinishi, og‘zaki va yozma nutq unsurlarining qorishib ketishi, qisqartmalar va so‘zlashuv birliklarining keng tarqalishi misollar orqali ko‘rib chiqiladi va qiyosiy tahlil qilinadi. Tadqiqotda tarixiy va zamonaviy til jarayonlari qiyosiy tahlil qilinib, adabiy til me’yorlarini saqlash va rivojlantirishda jadid matbuoti tajribasi hamda bugungi axborot makonining o‘rni asoslab beriladi.`,
                file: "/21.pdf", 
                keywords: "adabiy til, jadid matbuoti, ijtimoiy tarmoqlar, nutq, til jarayonlari, uslubiy me’yorlar."},
            { 
                slug: "abdurauf-fitrat-asarlarida-milliy-uygonish-goyalari",
                title: "ABDURAUF FITRAT ASARLARIDA MILLIY UYG‘ONISH G‘OYALARI", 
                author: "Mohira ERKINOVA", 
                page: "111-113", 
                date: "19.01.2026", 
                doi: "https://doi.org/10.5281/zenodo.19032947",
                abstract: `Ushbu tezisda Abdurauf Fitratning milliy uyg‘onish konsepsiyasi uning badiiy, publitsistik va pedagogik merosi asosida tahlil qilinadi. Fitrat milliy tiklanishni siyosiy mustaqillikdan avval ma’naviy-intellektual yuksalish bilan bog‘laydi, ta’lim tizimi va tafakkur yangiligi orqali xalqning tarixiy, madaniy va ma’naviy o‘zligini anglashini ta’kidlaydi. Tezisda “Munozara” asari misolida Fitratning usuli jadid maktablarini joriy etish, mustaqil fikr va tanqidiy tafakkur rivojlantirish g‘oyalari ko‘rsatib berilgan.`,
                file: "/22.pdf", 
                keywords: "Abdurauf Fitrat, milliy uyg‘onish, jadidchilik, ma’rifatparvarlik, ta’lim islohoti, usuli jadid, milliy o‘zlik."},
            { 
                slug: "siyosiy-lider-imijini-shakllantirishda-jadid-publitsistik-merosi-va-zamonaviy-mediastrategiyalari",
                title: "SIYOSIY LIDER IMIJINI SHAKLLANTIRISHDA JADID PUBLITSISTIK MEROSI VA ZAMONAVIY MEDIASTRATEGIYALARI", 
                author: "Munisaxon HASANOVA", 
                page: "113-116", 
                date: "19.01.2026", 
                doi: "https://doi.org/10.5281/zenodo.19032956",
                abstract: `Mazkur tezisda siyosiy lider imijini shakllantirish jarayonining tarixiy va zamonaviy jihatlari tahlil qilinib, ushbu jarayonda jadid publitsistik merosining tutgan o‘rni hamda zamonaviy media strategiyalarining ahamiyati qiyosiy yondashuv asosida o‘rganiladi. XX asr boshlarida shakllangan jadid publitsistikasi misolida milliy siyosiy yetakchi obrazini yaratishning g‘oyaviy, ma’naviy va mafkuraviy asoslari ochib beriladi hamda jadid mutafakkirlarining siyosiy yetakchilik haqidagi qarashlari tahlil qilinadi. Shuningdek, bugungi globallashuv va raqamlashtirish sharoitida siyosiy lider imijini shakllantirishda ommaviy axborot vositalari, ijtimoiy tarmoqlar va zamonaviy siyosiy kommunikatsiya texnologiyalarining o‘rni yoritiladi. Jadid publitsistikasi orqali shakllangan yetakchilik tamoyillari zamonaviy media makonida qo‘llanilayotgan imij yaratish strategiyalari bilan qiyoslab tahlil qilinadi. Tadqiqot natijasida jadid publitsistik merosi bugungi siyosiy kommunikatsiya jarayonlari uchun muhim nazariy va amaliy manba ekanligi asoslab beriladi.`,
                file: "/23.pdf", 
                keywords: "siyosiy lider, imij, jadid publitsistikasi, zamonaviy media, media strategiya, siyosiy kommunikatsiya, siyosiy yetakchilik."},
            { 
                slug: "jadid-matbuotining-milliy-jurnalistikada-tutgan-orni-va-ahamiyati",
                title: "JADID MATBUOTINING MILLIY JURNALISTIKADA TUTGAN O‘RNI VA AHAMIYATI", 
                author: "Azizbek CHORIYEV", 
                page: "117-122", 
                date: "19.01.2026", 
                doi: "https://doi.org/10.5281/zenodo.19032973",
                abstract: `Ushbu maqolada jadidchilik harakati yetakchisi Mahmudxo‘ja Behbudiyning publisistik merosi va uning g‘oyaviy yo‘nalishlari, o‘ziga xos uslubiy xususiyatlari haqida so‘z boradi. Shuningdek, Behbudiy publitsistikasining o‘ziga xos uslubiy jihatlari, muharrirlik faoliyatining milliy matbuot rivojidagi ahamiyati hamda maqolalarida ijtimoiy-siyosiy va madaniy-ma’rifiy muammolarning yoritilishi ko‘rsatib beriladi. Muallifning diniy-ma’rifiy qarashlari milliy ong va ma’naviy yangilanish jarayonlari bilan bog‘liq holda tahlil etiladi.`,
                file: "/24.pdf", 
                keywords: "Mahmudxoʻja Behbudiy, maʼrifatparvar, publisist, kemiruvchi illatlar, til oʻrganish, umuminsoniy tuygʻular, Vatan ravnaqi."},
            { 
                slug: "jadid-matbuoti-va-milliy-jurnalistika-ozod-sharafiddinov-talqinida-adabiyot-yashasa-–-millat-yashar",
                title: "JADID MATBUOTI VA MILLIY JURNALISTIKA: OZOD SHARAFIDDINOV TALQINIDA “ADABIYOT YASHASA – MILLAT YASHAR”", 
                author: "Qodir MURTOZOYEV", 
                page: "123-127", 
                date: "19.01.2026", 
                doi: "https://doi.org/10.5281/zenodo.19032981",
                abstract: `Mazkur maqolada jadid matbuotining milliy jurnalistika shakllanishidagi o‘rni hamda Ozod Sharafiddinovning Cho‘lpon adabiytanqidiy va publitsistik merosiga bergan talqini asosida tahlil qilinadi. Tadqiqotda “Adabiyot yashasa – millat yashar” g‘oyasi faqat adabiy-estetik qarash emas, balki jadid matbuoti va milliy jurnalistikaning ma’rifiy, ijtimoiy va mafkuraviy dasturi sifatida yoritiladi. Shuningdek, Sharafiddinovning Cho‘lponni jadid publitsisti va milliy jurnalistika konsepsiyasining muhim namoyandasi sifatida qayta baholashi ilmiy jihatdan asoslab beriladi.`,
                file: "/25.pdf", 
                keywords: "Jadid matbuoti, milliy jurnalistika, Cho‘lpon, Ozod Sharafiddinov, publitsistika, adabiy tanqid, milliy ong."},
            { 
                slug: "jadidlar-davrida-vaqtli-matbuot-marifat-milliy-uygonish-va-ijtimoiy-islohotlar-targibotida-gazeta-va-jurnallarning-orni",
                title: "JADIDLAR DAVRIDA VAQTLI MATBUOT: MA’RIFAT, MILLIY UYG‘ONISH VA IJTIMOIY ISLOHOTLAR TARG‘IBOTIDA GAZETA VA JURNALLARNING O‘RNI", 
                author: "Dilafruz YIGITALIYEVA", 
                page: "128-131", 
                date: "19.01.2026", 
                doi: "https://doi.org/10.5281/zenodo.19032991",
                abstract: `Mazkur maqolada jadidlar davrida nashr etilgan gazeta va jurnallarning ijtimoiy ahamiyati, shuningdek, ularning dizayni, tuzilishi va xususiyatlari tarixiy manbalar asosida tahlil qilinadi. Ushbu maqolada jadidlar davrida nashr etilgan vaqtli matbuot nashrlarini mazmuniy yo‘nalishi, intellektual ahamiyati, tuzilishi va shakliy hususiyatlarini chuqur yoritilgan.`,
                file: "/26.pdf", 
                keywords: "Mafkuraviy qurol, jadid ziyolilari, milliy uyg‘onish, ongini uyg‘otish, erkinlik, ozodlik, mafkuraviy qurol."},
            { 
                slug: "fitrat-as-a-publicist-and-editor-his-role-in-the-development-of-jadid-journalism-and-national-consciousness",
                title: "FITRAT AS A PUBLICIST AND EDITOR - HIS ROLE IN THE DEVELOPMENT OF JADID JOURNALISM AND NATIONAL CONSCIOUSNESS", 
                author: "Jasmina CHORIYEVA", 
                page: "132-135", 
                date: "19.01.2026", 
                doi: "https://doi.org/10.5281/zenodo.19032997",
                abstract: `This article examines the multifaceted activity of Abdurauf Fitrat as a publicist and editor, highlighting his decisive role in the formation of Jadid journalism and the modernization of national consciousness in Central Asia at the beginning of the twentieth century. Fitrat’s journalistic and editorial legacy is analyzed in the context of socio-political transformations, cultural awakening, and educational reform. Special attention is paid to his contributions to Jadid periodicals, his editorial principles, language and style, and his influence on the ideological orientation of the national press. The study demonstrates that Fitrat’s publicism served not only as a means of information dissemination but also as a powerful instrument of social mobilization and intellectual renewal.`,
                file: "/27.pdf", 
                keywords: "Abdurauf Fitrat, Jadid journalism, publicism, editorial activity, national press, modernization, intellectual heritage"},
            { 
                slug: "jadid-matbuotining-milliy-jurnalistika-taraqqiyotidagi-orni",
                title: "JADID MATBUOTINING MILLIY JURNALISTIKA TARAQQIYOTIDAGI O‘RNI", 
                author: "Hojiakbar MAXAMADJANOV", 
                page: "136-143", 
                date: "19.01.2026", 
                doi: "https://doi.org/10.5281/zenodo.19033017",
                abstract: `Mazkur ilmiy maqolada XX asr boshlarida Turkistonda shakllangan jadid matbuotining milliy jurnalistika taraqqiyotidagi o‘rni, uning g‘oyaviyma’rifiy yo‘nalishlari hamda ijtimoiysiyosiy ongni shakllantirishdagi tarixiy ahamiyati kompleks tahlil qilinadi. Tadqiqotda jadidchilik harakati doirasida vujudga kelgan “Taraqqiy”, “Hurriyat”, “Ishtirokiyun”, “Shuhrat”, “Osiyo”, “Mushtum” kabi nashrlar materiallari asosida jadid publitsistikasining asosiy mavzulari — hurriyat va istiqlol g‘oyasi, mustaqil Turkiston davlati barpo etish masalasi, xalqni ilm-ma’rifatga chorlash, milliy til va madaniyatni asrash, mustamlakachilik va zo‘ravon siyosatga qarshi tanqidiy munosabatlar yoritilgan. Maqolada Ismoil Obidiy, Mahmudxo‘ja Behbudiy, Abdurauf Fitrat, Abdulla Avloniy, Hoji Muin, Abdulla Qodiriy kabi jadid mutafakkirlarining publitsistik merosi tahlil qilinib, ularning milliy jurnalistika rivojiga qo‘shgan hissasi ilmiy asosda ochib berilgan. Jadid matbuotining xalqona va ta’sirchan tili, badiiy publitsistika va felyeton janrining shakllanishidagi o‘rni, matbuot orqali milliy o‘zlikni anglash va ijtimoiy adolat g‘oyalarini targ‘ib etish usullari tahlil markaziga qo‘yilgan. Shuningdek, tadqiqotda jadidchilik g‘oyalarining bugungi Yangi O‘zbekiston taraqqiyot strategiyasi bilan uzviy bog‘liqligi asoslanib, jadid matbuoti tajribasini zamonaviy jurnalistika va yosh kadrlar tayyorlash jarayonida metodik manba sifatida qo‘llash zarurligi ilmiy xulosalar bilan ifodalangan.`,
                file: "/28.pdf", 
                keywords: "jadid matbuoti, milliy jurnalistika taraqqiyoti, jadidchilik harakati, Turkiston jadidlari, publitsistika tarixi, milliy uyg‘onish, hurriyat va istiqlol g‘oyasi, mustaqil Turkiston konsepsiyasi, jadid publitsistikasi, felyeton janri, ma’rifatparvarlik g‘oyalari, milliy til va matbuot, ijtimoiy tanqid, Yangi O‘zbekiston va jadidlar merosi."},
            { 
                slug: "prikladnye-aspekty-politicheskoj-reklami",
                title: "ПРИКЛАДНЫЕ АСПЕКТЫ ПОЛИТИЧЕСКОЙ РЕКЛАМЫ НА ЭЛЕКТОРАЛЬНОЕ ПОВЕДЕНИЕ ГРАЖДАН ТАДЖИКИСТАНА: СОЦИАЛЬНЫЙ АНАЛИЗ", 
                author: "И.И.Хамидиён & Б.С.Мансурова", 
                page: "144-154", 
                date: "19.01.2026", 
                doi: "https://doi.org/10.5281/zenodo.19033169",
                abstract: ``,
                file: "/29.pdf", },
            { 
                slug: "modern-journalism-trends-new-formats-and-social-media-development-within-the-political-line-of-president-ilham-aliyev",
                title: `MODERN JOURNALISM: TRENDS, NEW FORMATS, AND SOCIAL MEDIA DEVELOPMENT WITHIN THE POLITICAL LINE OF PRESIDENT ILHAM ALIYEV`, 
                author: "Babayeva-Şükürova Fərahilə", 
                page: "155-157", 
                date: "19.01.2026", 
                doi: "https://doi.org/10.5281/zenodo.19033181",
                abstract: ``,
                file: "/30.pdf", 
                keywords: "modern journalism, social media, new media formats, media policy, President Ilham Aliyev"},
            { 
                slug: "analiticheskie-zhanry-i-socialьnaya-zhurnalistika-kak-instrument-osmysleniya-i-obsuzhdeniya-problem-sfery-obrazovaniya-v-mestnoj-periodicheskoj-presse-tadzhikistana-issledovanie-na-primere-materialov-gazety-«hatlon»",
                title: "АНАЛИТИЧЕСКИЕ ЖАНРЫ И СОЦИАЛЬНАЯ ЖУРНАЛИСТИКА КАК ИНСТРУМЕНТ ОСМЫСЛЕНИЯ И ОБСУЖДЕНИЯ ПРОБЛЕМ СФЕРЫ ОБРАЗОВАНИЯ В МЕСТНОЙ ПЕРИОДИЧЕСКОЙ ПРЕССЕ ТАДЖИКИСТАНА (исследование на примере материалов газеты «Хатлон»)", 
                author: "Маъмурзода Носирджон Маъмур & Хайрзода Рамазон Ашурали", 
                page: "158-173", 
                date: "19.01.2026", 
                doi: "https://doi.org/10.5281/zenodo.19033191",
                abstract: ``,
                file: "/31.pdf", 
                keywords: "политическая реклама, Таджикистан, методы, задача, аутсорсинг, политическая коммуникация, выборы, НДПТ, законодательство, политические партии, кандидат, электорат, рекламодатель."},
            { 
                slug: "media-kak-faktor-formirovaniya-obshestvennogo-immuniteta-k-radikalizmu",
                title: "МЕДИА КАК ФАКТОР ФОРМИРОВАНИЯ ОБЩЕСТВЕННОГО ИММУНИТЕТА К РАДИКАЛИЗМУ", 
                author: "Малика АХМЕДОВА", 
                page: "174-179", 
                date: "19.01.2026", 
                doi: "https://doi.org/10.5281/zenodo.19033210",
                abstract: ``,
                file: "/32.pdf", 
                keywords: "медиа, радикализм, профилактика экстремизма, общественный иммунитет, информационная безопасность, медиаграмотность, медиадискурс, толерантность."},
            { 
                slug: "baspa-isinde-redaktorliq-jumis-ham-tekst-sapasin-tamiyinlewdin-geypara-maseleleri",
                title: "BASPA ISINDE REDAKTORLIQ JUMÍS HÁM TEKST SAPASÍN TÁMIYINLEWDIŃ GEYPARA MÁSELELERI", 
                author: "Masharipova T.J. & Maratova S.M.", 
                page: "180-183", 
                date: "19.01.2026", 
                doi: "https://doi.org/10.5281/zenodo.19033226",
                abstract: ``,
                file: "/33.pdf", 
                keywords: "Baspa isi, redaktor, redaktorlıq, tekst, teksttiń bir pútinligi, avtorlıq tekst, original nusqa."},
            { 
                slug: "journalism-and-newspaper-writing",
                title: "JOURNALISM AND NEWSPAPER WRITING", 
                author: "Kenan Novruzov", 
                page: "184-188", 
                date: "19.01.2026", 
                doi: "https://doi.org/10.5281/zenodo.19033237",
                abstract: ``,
                file: "/34.pdf", 
                keywords: "journalism, press, media, information and communication technologies, newspaper"},
            { 
                slug: "boqiy-meros-charchashmalari-yoxud-saydi-umirov-publitsistikasida-jadidshunos-olimlar-ijodi-tahlili",
                title: "BOQIY MEROS CHARCHASHMALARI YOXUD SAYDI UMIROV PUBLITSISTIKASIDA JADIDSHUNOS OLIMLAR IJODI TAHLILI", 
                author: "Zulfiya FAYZULLAYEVA", 
                page: "189-192", 
                date: "19.01.2026", 
                doi: "https://doi.org/10.5281/zenodo.19033247",
                abstract: ``,
                file: "/35.pdf", 
                keywords: "jadidchilik, ma’rifatparvarlik, jadidshunoslik, matbuot, qatag‘on, ma’naviyat, publitsist."},
            { 
                slug: "fijet-haqida-eshitganmisiz",
                title: "FIJET HAQIDA ESHITGANMISIZ?", 
                author: "Munira ISOMIDDINOVA", 
                page: "193-196", 
                date: "19.01.2026", 
                doi: "https://doi.org/10.5281/zenodo.19033257",
                abstract: ``,
                file: "/36.pdf",},
            { 
                slug: "transformaciya-zhurnalistiki-v-konvergentnoe-media",
                title: "ТРАНСФОРМАЦИЯ ЖУРНАЛИСТИКИ В КОНВЕРГЕНТНОЕ МЕДИА", 
                author: "Назокат ХАМРАКУЛОВА", 
                page: "197-206", 
                date: "19.01.2026", 
                doi: "https://doi.org/10.5281/zenodo.19033267",
                abstract: ``,
                file: "/37.pdf", 
                keywords: "медиасфера, контент, медиаиндустрия, цифровизация, медиаконвергенция, медиаландшафт."},
            { 
                slug: "raqamli-muhitdagi-salbiy-tendensiyalar-clickbait-va-manipulyatsiya",
                title: "RAQAMLI MUHITDAGI SALBIY TENDENSIYALAR: CLICKBAIT VA MANIPULYATSIYA", 
                author: "Iroda MURODJONOVA", 
                page: "207-210", 
                date: "19.01.2026", 
                doi: "https://doi.org/10.5281/zenodo.19033278",
                abstract: ``,
                file: "/38.pdf", 
                keywords: "raqamli media, clickbait, manipulyatsiya, ommaviy kommunikatsiya, algoritmik ta’sir, axborot xavfsizligi, media savodxonlik."},
            { 
                slug: "suniy-intellekt-yordamida-ijtimoiy-tarmoqlarda-salbiy-sentimentni-aniqlash-mexanizmlari",
                title: "SUN’IY INTELLEKT YORDAMIDA IJTIMOIY TARMOQLARDA SALBIY SENTIMENTNI ANIQLASH MEXANIZMLARI", 
                author: "Gulmira SHUKUROVA", 
                page: "211-213", 
                date: "19.01.2026", 
                doi: "https://doi.org/10.5281/zenodo.19033302",
                abstract: ``,
                file: "/39.pdf", 
                keywords: "Sun’iy intellekt, sentiment tahlili, inqiroz kommunikatsiyasi, ijtimoiy tarmoqlar, PR monitoring"},
            { 
                slug: "destruktiv-tashkilotlar-millatlararo-totuvlik-masalalarini-mediada-yoritilishi",
                title: "DESTRUKTIV TASHKILOTLAR, MILLATLARARO TOTUVLIK MASALALARINI MEDIADA YORITILISHI", 
                author: "Dildora RIZAYEVA", 
                page: "214-218", 
                date: "19.01.2026", 
                doi: "https://doi.org/10.5281/zenodo.19033334",
                abstract: ``,
                file: "/40.pdf", 
                keywords: "Tinchlik, barqarorlik, tolerantlik, media, internet, OAV, ijtimoiy tarmoq, jurnalistika, terrorchilik, destruktiv tashkilotlar, buzg‘unchi g‘oyalar."},
            { 
                slug: "koreys-va-ozbek-tillarida-boglovchilarning-morfologik-va-sintaktik-orni",
                title: "KOREYS VA O‘ZBEK TILLARIDA BOG‘LOVCHILARNING MORFOLOGIK VA SINTAKTIK O‘RNI", 
                author: "Dilnoza BAXRANOVA & Jasmina RAFIQOVA", 
                page: "219-222", 
                date: "19.01.2026", 
                doi: "https://doi.org/10.5281/zenodo.19033348",
                abstract: ``,
                file: "/41.pdf", 
                keywords: "bog‘lovchi, morfologiya, sintaksis, qiyosiy tahlil, grammatik birlik, koordinat bog‘lovchi, subordinat bog‘lovchi, tilshunoslik."},
            { 
                slug: "zamonaviy-onlayn-oavda-ekologik-kontent-ishlab-chiqish-tendensiyalari-suv-muammolari-mavzusining-media-formatlar-orqali-talqini",
                title: "ZAMONAVIY ONLAYN OAVDA EKOLOGIK KONTENT ISHLAB CHIQISH TENDENSIYALARI: SUV MUAMMOLARI MAVZUSINING MEDIA FORMATLAR ORQALI TALQINI", 
                author: "Malika SABUROVA", 
                page: "223-229", 
                date: "19.01.2026", 
                doi: "https://doi.org/10.5281/zenodo.19033367",
                abstract: ``,
                file: "/42.pdf", 
                keywords: "ekologik kontent, suv muammolari, zamonaviy jurnalistika, media formatlar, raqamli OAV"},
            { 
                slug: "osoznanie-nakazaniya-i-vnutrennyaya-transformaciya-personazhej-v-romane-kon-dzhijona-«nashi-schastlivye-vremena»",
                title: "ОСОЗНАНИЕ НАКАЗАНИЯ И ВНУТРЕННЯЯ ТРАНСФОРМАЦИЯ ПЕРСОНАЖЕЙ В РОМАНЕ КОН ДЖИЙОНА «НАШИ СЧАСТЛИВЫЕ ВРЕМЕНА»", 
                author: "Ситора ТУРАКУЛОВА", 
                page: "230-235", 
                date: "19.01.2026", 
                doi: "https://doi.org/10.5281/zenodo.19033384",
                abstract: ``,
                file: "/43.pdf", 
                keywords: "внутренняя трансформация; осознание наказания; раскаяние; вина; прощение; внутренние переживания; эмоциональная травма; духовное исцеление; тюремная литература; гуманизм; межличностное понимание; экзистенциальный кризис."},
            { 
                slug: "gibrid-til-tillar-aloqasi-va-madaniy-ozaro-tasir-mahsuli",
                title: "GIBRID TIL: TILLAR ALOQASI VA MADANIY O‘ZARO TA’SIR MAHSULI", 
                author: "Gulmira ESHQUVVATOVA & Zebo KARIMOVA", 
                page: "236-239", 
                date: "19.01.2026", 
                doi: "https://doi.org/10.5281/zenodo.19033396",
                abstract: ``,
                file: "/44.pdf", 
                keywords: "gibrid til, tillar aloqasi, ikki tillilik, kod almashtirish, intertil (interlanguage), madaniy o‘zaro ta’sir, sotsiolingvistika, lingvistik gibridlik."},
            { 
                slug: "real-voqealarga-asoslangan-seriallar-televizion-mahsulot-sifatida",
                title: "REAL VOQEALARGA ASOSLANGAN SERIALLAR TELEVIZION MAHSULOT SIFATIDA", 
                author: "Xurshidabonu NAZAROVA", 
                page: "240-242", 
                date: "19.01.2026", 
                doi: "https://doi.org/10.5281/zenodo.19035202",
                abstract: ``,
                file: "/45.pdf", 
                keywords: "realiti-shou, media makon, kommunikasiya, ommaviy madaniyat, uyushtirilgan haqiqat, teleserial, dramaturgiya."},
            { 
                slug: "sformirovanie-fotopublicistiki-v-pervyh-karakalpakskih-gazetah",
                title: "СФОРМИРОВАНИЕ ФОТОПУБЛИЦИСТИКИ В ПЕРВЫХ КАРАКАЛПАКСКИХ ГАЗЕТАХ", 
                author: "Халима ХАЛИЛАЕВА", 
                page: "243-248", 
                date: "19.01.2026", 
                doi: "https://doi.org/10.5281/zenodo.19035216",
                abstract: ``,
                file: "/46.pdf", },
            { 
                slug: "vliyanie-socialьnyh-media-na-sovremennuyu-zhurnalistiku-v-usloviyah-cifrovizacii-mediaprostranstva",
                title: "ВЛИЯНИЕ СОЦИАЛЬНЫХ МЕДИА НА СОВРЕМЕННУЮ ЖУРНАЛИСТИКУ В УСЛОВИЯХ ЦИФРОВИЗАЦИИ МЕДИАПРОСТРАНСТВА", 
                author: "Дурдана ПЕРДЕБАЕВА", 
                page: "249-253", 
                date: "19.01.2026", 
                doi: "https://doi.org/10.5281/zenodo.19035225",
                abstract: ``,
                file: "/47.pdf", 
                keywords: "социальные медиа, журналистика, цифровые медиа, медиапотребление, медиаэтика, дезинформация, алгоритмы."},
            { 
                slug: "internet-matnlarida-yangi-inovatsion-iboralarning-stilistik-xususiyatlari",
                title: "INTERNET MАTNLАRIDА YANGI INOVATSION IBORALARNING STILISTIK XUSUSIYАTLАRI", 
                author: "Gulmira ESHQUVVATOVA", 
                page: "254-262", 
                date: "19.01.2026", 
                doi: "https://doi.org/10.5281/zenodo.19035237",
                abstract: ``,
                file: "/48.pdf", 
                keywords: "internet matni, internet frazeologizmlari, stilistik xususiyat, semantik kengayish, pragmatik baho, kod aralashuvi"},
            { 
                slug: "global-mediada-yechimlar-jurnalistikasining-vujudga-kelishi-va-taraqqiyoti",
                title: "GLOBAL MEDIADA YECHIMLAR JURNALISTIKASINING VUJUDGA KELISHI VA TARAQQIYOTI", 
                author: "Nodira SULEYMONOVA", 
                page: "263-268", 
                date: "19.01.2026", 
                doi: "https://doi.org/10.5281/zenodo.19035252",
                abstract: ``,
                file: "/49.pdf", 
                keywords: "yechimlar jurnalistikasi, global media, konstruktiv jurnalistika, dalillarga asoslangan reportaj, jurnalistika nazariyasi, auditoriya ishonchi."},
            { 
                slug: "mediahajp-v-epohu-cifrovyh-platform-algoritmy-vnimaniya-i-transformaciya-sovremennoj-zhurnalistiki",
                title: "МЕДИАХАЙП В ЭПОХУ ЦИФРОВЫХ ПЛАТФОРМ: АЛГОРИТМЫ ВНИМАНИЯ И ТРАНСФОРМАЦИЯ СОВРЕМЕННОЙ ЖУРНАЛИСТИКИ", 
                author: "Зарифа ТАЖИЕВА", 
                page: "269-277", 
                date: "19.01.2026", 
                doi: "https://doi.org/10.5281/zenodo.19035258",
                abstract: ``,
                file: "/50.pdf", 
                keywords: "Медиахайп, цифровые платформы, алгоритмы внимания, экономика внимания, платформенная журналистика, искусственный интеллект"},
            { 
                slug: "jadid-matbuotida-xotinqizlar-ijtimoiy-faolligi-masalasining-yoritilishi",
                title: "JADID MATBUOTIDA XOTINQIZLAR IJTIMOIY FAOLLIGI MASALASINING YORITILISHI", 
                author: "Sayyora KADIROVA", 
                page: "278-280", 
                date: "19.01.2026", 
                doi: "https://doi.org/10.5281/zenodo.19035269",
                abstract: ``,
                file: "/51.pdf", 
                keywords: "Jadidchilik, jadid matbuoti, xotin-qizlar, ijtimoiy faollik, ma’rifat, ayollar ta’limi, Abdurauf Fitrat, Mahmudxo‘ja Behbudiy"},
            { 
                slug: "development-trends-in-modern-journalism-perception-of-the-quality-of-news-content-in-the-mass-media",
                title: "DEVELOPMENT TRENDS IN MODERN JOURNALISM PERCEPTION OF THE QUALITY OF NEWS CONTENT IN THE MASS MEDIA", 
                author: "Zulkhumor SOLIEVA", 
                page: "281-284", 
                date: "19.01.2026", 
                doi: "https://doi.org/10.5281/zenodo.19035289",
                abstract: ``,
                file: "/52.pdf", 
                keywords: "news content quality, information reliability, news presentation, society and mass media."},
            { 
                slug: "jurnalistika-taraqqiyot-tendensiyalari",
                title: "JURNALISTIKA TARAQQIYOT TENDENSIYALARI", 
                author: "Muhlisa KAMOLOVA", 
                page: "285-287", 
                date: "19.01.2026", 
                doi: "https://doi.org/10.5281/zenodo.19035307",
                abstract: ``,
                file: "/53.pdf", 
                keywords: "jurnalistika, taraqqiyot, multimediya, internet jurnalistika, kasbiy etika, raqamlashtirish."},
            { 
                slug: "ijtimoiy-tarmoqlarda-bolalarga-oid-kontentlarda-etik-meyorlarga-amal-qilish-masalasi",
                title: "IJTIMOIY TARMOQLARDA BOLALARGA OID KONTENTLARDA ETIK MEYORLARGA AMAL QILISH MASALASI", 
                author: "Orzugul KARIMOVA", 
                page: "288-291", 
                date: "19.01.2026", 
                doi: "https://doi.org/10.5281/zenodo.19035315",
                abstract: ``,
                file: "/54.pdf", 
                keywords: "Ijtimoiy tarmoqlar, bolalar kontenti, etik me’yorlar, axborot xavfsizligi, raqamli mas’uliyat."},
            { 
                slug: "bolalar-uchun-moljallangan-internet-loyihalarda-auditoriya-bilan-ishlash-strategiyalari-youtube-kanallar-misolida",
                title: "BOLALAR UCHUN MO‘LJALLANGAN INTERNET LOYIHALARDA AUDITORIYA BILAN ISHLASH STRATEGIYALARI (YOUTUBE KANALLAR MISOLIDA)", 
                author: "Gulnoza BEGIMQULOVA", 
                page: "292-293", 
                date: "19.01.2026", 
                doi: "https://doi.org/10.5281/zenodo.19035325",
                abstract: ``,
                file: "/55.pdf", 
                keywords: "YouTube, bolalar media loyihalari, auditoriya strategiyasi, yangi formatlar, raqamli jurnalistika, ijtimoiy media, interaktivlik."},
            { 
                slug: "behbudiyning-marifatparvarlik-faoliyati",
                title: "BEHBUDIYNING MA`RIFATPARVARLIK FAOLIYATI", 
                author: "Muqaddas QURBONOVA", 
                page: "298-301", 
                date: "19.01.2026", 
                doi: "https://doi.org/10.5281/zenodo.19035345",
                abstract: ``,
                file: "/57.pdf", 
                keywords: "Ayollar huquqlari, gender tengligi, jadidchilik harakati, ayollar ta’limi, Mahmudxo‘ja Behbudiy, Abdulla Avloniy, ijtimoiy tenglik, Abdurauf Fitrat."},
            { 
                slug: "jadid-matbuotida-ijodiy-boshqaruvning-oziga-xosligi",
                title: "JADID MATBUOTIDA IJODIY BOSHQARUVNING O‘ZIGA XOSLIGI", 
                author: "Maftuna ABDUKARIMOVA", 
                page: "302-308", 
                date: "19.01.2026", 
                doi: "https://doi.org/10.5281/zenodo.19035360",
                abstract: ``,
                file: "/58.pdf", 
                keywords: "Ayollar huquqlari, gender tengligi, jadidchilik harakati, ayollar ta’limi, Mahmudxo‘ja Behbudiy, Abdulla Avloniy, ijtimoiy tenglik, Abdurauf Fitrat."},
];

export async function generateMetadata({ params }) {

  const { slug } = await params;
  const article = articles.find(a => a.slug === slug);

  if (!article) return {};

  return {
    title: article.title,
    description: article.abstract,

    authors: [{ name: article.author }],

    other: {
      citation_title: article.title,
      citation_author: article.author,
      citation_publication_date: article.date,
      citation_pdf_url: article.pdf,
      citation_doi: article.doi,
      citattion_abstract: article.abstract,
      citation_language: "uz",
      citation_online_date: article.date
    }
  };
}

export default async function ArticlePage({ params }) {

  const { slug } = await params;   
  const article = articles.find(a => a.slug === slug);

  if (!article) {
    notFound();
  }

  return (
    <section className="articlePage">
      <h1>{article.title}</h1>
      <div className="articlePageMain">
        <div className="articlePageInfo">
          <h2><strong>{article.author}</strong></h2>
          <h3 style={{fontWeight: "normal"}}><strong>DOI:</strong> <a href={article.doi} target="_blank">{article.doi}</a></h3>
          <h3 style={{fontWeight: "normal"}}><strong>Annotatsiya:</strong> {article.abstract}</h3>
          <h3 style={{fontWeight: "normal"}}><strong>Kalit so'zlar:</strong> {article.keywords}</h3>
          <h3>{article.page}</h3>
          <a href={article.file} className="articleBtn" download>Yuklash</a>
        </div>
        <div className="articlePageImg">
          <img src="/conf.png" alt="" />
          <p><strong>{article.date}</strong></p>
        </div>
      </div>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: JSON.stringify({
          "@context": "https://schema.org",
          "@type": "ScholarlyArticle",
          headline: article.title,
          author: {
            "@type": "Person",
            name: article.author
          },
          description: article.abstract,
          keywords: article.keywords,
          datePublished: article.date,
          identifier: article.doi,
          url: `https://jadidmedia.uz/article/${article.slug}`
          })
        }}
        />
    </section>
  );
}