import ArticleList from "./ArticleList";

const variations = {
    "1": {
        title: "MAHMUDXO‘JA BEHBUDIYNING PUBLITSISTIK MEROSI",
        articles: [
            {id: 1, 
                slug: "behbudi-global-tafakkuri", 
                title: "MAHMUDXO‘JA BEHBUDIYNING GLOBAL TAFAKKURI: TARIXIY TAJRIBA VA BUGUNGI SABOQLAR", 
                author: "A’zamjon DADAXONOV", 
                page: "12-16", 
                date: "19.01.2026", 
                keywords: "Mahmudxo‘ja Behbudiy, jadidchilik, xalqaro dunyoqarash, G‘arb sivilizatsiyasi, modernizatsiya, matbuot, ta’lim islohoti.",
                file: "/1.pdf"
            },
            {id: 2, 
                slug: "mahmudxoja-behbudiy-ijodi-va-faoliyatida-turkiy-xalqlarning-ozodligi-hamda-birlashuviga-bolgan-etibor",
                title: `MАHMUDXO‘JА BEHBUDIY IJODI VА FАOLIYATIDА TURKIY XАLQLАRNING OZODLIGI HАMDА BIRLАSHUVIGА BO‘LGАN E’TIBOR`, 
                author: "Barchinoy JO‘RAEVA", 
                page: "12-16", 
                date: "19.01.2026", 
                keywords: "Mahmudxo‘ja Behbudiy, jadidchilik, xalqaro dunyoqarash, G‘arb sivilizatsiyasi, modernizatsiya, matbuot, ta’lim islohoti.",
                file: "/1.pdf"},
            {id: 3, 
                slug: "mahmudxoja-behbudiy-maqolalarida-ijtimoiy-siyosiy-muammolarning-aks-etishi",
                title: "MAHMUDXO‘JA BEHBUDIY MAQOLALARIDA IJTIMOIY-SIYOSIY MUAMMOLARNING AKS ETISHI", 
                author: "Sitora SHOKIROVA & Diyorbek TURAYEV", 
                page: "12-16", 
                date: "19.01.2026", 
                keywords: "Mahmudxo‘ja Behbudiy, jadidchilik, xalqaro dunyoqarash, G‘arb sivilizatsiyasi, modernizatsiya, matbuot, ta’lim islohoti.",
                file: "/1.pdf"},
            {id: 4, 
                slug: "mahmudxoja-behbudiyning-publitsistik-merosi-va-uning-bugungi-ahamiyati",
                title: "MAHMUDXOʻJA BEHBUDIYNING PUBLITSISTIK MEROSI VA UNING BUGUNGI AHAMIYATI", 
                author: "Gulhayo AKRAMOVA", 
                page: "29-30", 
                date: "19.01.2026", 
                keywords: "Mahmudxo‘ja Behbudiy, jadidchilik, xalqaro dunyoqarash, G‘arb sivilizatsiyasi, modernizatsiya, matbuot, ta’lim islohoti.",
                file: "/1.pdf"},
            {id: 5, 
                slug: "behbudiy-ijodida-teatr-sanati",
                title: "BEHBUDIY IJODIDA TEATR SAN’ATI", 
                author: "Izzatilla ZOHIDJONOV", 
                page: "31-33", 
                date: "19.01.2026", 
                keywords: "Mahmudxo‘ja Behbudiy, jadidchilik, xalqaro dunyoqarash, G‘arb sivilizatsiyasi, modernizatsiya, matbuot, ta’lim islohoti.",
                file: "/1.pdf"},
            {id: 6,
                slug: "mahmudxoja-behbudiy-publisistikasida-tanqid-va-ijtimoiy-illatlar-masalasi", 
                title: "MAHMUDXO‘JA BEHBUDIY PUBLISISTIKASIDA TANQID VA IJTIMOIY ILLATLAR MASALASI", 
                author: "Mashhura JO‘RAQULOVA", 
                page: "34-36", 
                date: "19.01.2026", 
                keywords: "Mahmudxo‘ja Behbudiy, jadidchilik, xalqaro dunyoqarash, G‘arb sivilizatsiyasi, modernizatsiya, matbuot, ta’lim islohoti.",
                file: "/1.pdf"},
            {id: 7, 
                slug: "mahmudxoja-behbudiy-publitsistikasidagi-dolzarblik-masalalari",
                title: "MAHMUDXO‘JA BEHBUDIY PUBLITSISTIKASIDAGI DOLZARBLIK MASALALARI", 
                author: "Timur USUPOV & Shahribonu TURIKOVA", 
                page: "37-41", 
                date: "19.01.2026", 
                keywords: "Mahmudxo‘ja Behbudiy, jadidchilik, xalqaro dunyoqarash, G‘arb sivilizatsiyasi, modernizatsiya, matbuot, ta’lim islohoti.",
                file: "/1.pdf"},
            {id: 8, 
                slug: "turkiston-jadidlik-harakati-asoschisi",
                title: "TURKISTON JADIDLIK HARAKATI ASOSCHISI", 
                author: "Dilnavoz RIZAYEVA", 
                page: "42-45", 
                date: "19.01.2026", 
                keywords: "Mahmudxo‘ja Behbudiy, jadidchilik, xalqaro dunyoqarash, G‘arb sivilizatsiyasi, modernizatsiya, matbuot, ta’lim islohoti.",
                file: "/1.pdf"},
        ]
    },
    "2": {
        title: "JADID MATBUOTINING MILLIY JURNALISTIKADA TUTGAN O‘RNI VA AHAMIYATI",
        articles: [
            {id: 1, 
                slug: "sovet-axborot-siyosati-va-matbuoti-prinsiplari",
                title: "SOVET AXBOROT SIYOSATI VA MATBUOTI PRINSIPLARI", 
                author: "Nilufar NAMAZOVA", 
                page: "46-49", 
                date: "19.01.2026", 
                keywords: "Mahmudxo‘ja Behbudiy, jadidchilik, xalqaro dunyoqarash, G‘arb sivilizatsiyasi, modernizatsiya, matbuot, ta’lim islohoti.",
                file: "/1.pdf"},
            {id: 2, 
                slug: "ozbek-va-tatar-adabiy-aloqalari-behbudiy-va-tatar-ijodkorlari-misolida",
                title: `O‘ZBEK VA TATAR ADABIY ALOQALARI (BEHBUDIY VA TATAR IJODKORLARI MISOLIDA)`, 
                author: "Gulzoda SOATOVA", 
                page: "50-59",
                date: "19.01.2026", 
                keywords: "Mahmudxo‘ja Behbudiy, jadidchilik, xalqaro dunyoqarash, G‘arb sivilizatsiyasi, modernizatsiya, matbuot, ta’lim islohoti.",
                file: "/1.pdf"},
            {id: 3, 
                slug: "abdulla-qodiriy-publisistikasida-ijtimoiy-masalalarning-yoritilishi",
                title: "ABDULLA QODIRIY PUBLISISTIKASIDA IJTIMOIY MASALALARNING YORITILISHI", 
                author: "Oydin TURDIYEVA & Jahongir TURDIYEV", 
                page: "60-64", 
                date: "19.01.2026", 
                keywords: "Mahmudxo‘ja Behbudiy, jadidchilik, xalqaro dunyoqarash, G‘arb sivilizatsiyasi, modernizatsiya, matbuot, ta’lim islohoti.",
                file: "/1.pdf"},
            {id: 4, 
                slug: "xx-asr-ozbek-ayollar-adabiyoti-oydin-sobirova-va-uning-ijodiy-merosi",
                title: "XX ASR O‘ZBEK AYOLLAR ADABIYOTI: OYDIN SOBIROVA VA UNING IJODIY MEROSI", 
                author: "Shaxlo BAZAROVA", 
                page: "65-69", 
                date: "19.01.2026", 
                keywords: "Mahmudxo‘ja Behbudiy, jadidchilik, xalqaro dunyoqarash, G‘arb sivilizatsiyasi, modernizatsiya, matbuot, ta’lim islohoti.",
                file: "/1.pdf"},
            {id: 5, 
                slug: "samarqand-jadidchilik-maktabining-asoschisi-akademik-said-rizo-alizodaning-hayot-yoli",
                title: "SAMARQAND JADIDCHILIK MAKTABINING ASOSCHISI AKADEMIK SAID RIZO ALIZODANING HAYOT YO’LI", 
                author: "Mirzoulug’bek YUSUPOV", 
                page: "70-72", 
                date: "19.01.2026", 
                keywords: "Mahmudxo‘ja Behbudiy, jadidchilik, xalqaro dunyoqarash, G‘arb sivilizatsiyasi, modernizatsiya, matbuot, ta’lim islohoti.",
                file: "/1.pdf"},
            {id: 6, 
                slug: "fitratning-sharq-siyosati-risolasida-xx-asr-dunyo-siyosiy-manzarasi-tahlili",
                title: "FITRATNING “SHARQ SIYOSATI” RISOLASIDA XX ASR DUNYO SIYOSIY MANZARASI TAHLILI", 
                author: "Shohruxbek OLIMOV", 
                page: "73-79", 
                date: "19.01.2026", 
                keywords: "Mahmudxo‘ja Behbudiy, jadidchilik, xalqaro dunyoqarash, G‘arb sivilizatsiyasi, modernizatsiya, matbuot, ta’lim islohoti.",
                file: "/1.pdf"},
            {id: 7, 
                slug: "jadidlar-nigohida-oila-va-ayol-fitrat-qarashlari-misolida",
                title: "JADIDLAR NIGOHIDA OILA VA AYOL: FITRAT QARASHLARI MISOLIDA", 
                author: "Nigora ELMURODOVA", 
                page: "80-84", 
                date: "19.01.2026", 
                keywords: "Mahmudxo‘ja Behbudiy, jadidchilik, xalqaro dunyoqarash, G‘arb sivilizatsiyasi, modernizatsiya, matbuot, ta’lim islohoti.",
                file: "/1.pdf"},
            {id: 8, 
                slug: "rauf-muzaffarzoda-publitsistikasida-marifat-va-taraqqiyot-masalalari",
                title: "RAUF MUZAFFARZODA PUBLITSISTIKASIDA MA’RIFAT VA TARAQQIYOT MASALALARI", 
                author: "Ozoda YUSUPOVA", 
                page: "85-87", 
                date: "19.01.2026", 
                keywords: "Mahmudxo‘ja Behbudiy, jadidchilik, xalqaro dunyoqarash, G‘arb sivilizatsiyasi, modernizatsiya, matbuot, ta’lim islohoti.",
                file: "/1.pdf"},
            {id: 9, 
                slug: "said-rizo-alizodaning-turkiston-jadidchiligiga-qoshgan-hissasi",
                title: "SAID RIZO ALIZODANING TURKISTON JADIDCHILIGIGA QO‘SHGAN HISSASI", 
                author: "Yunus Safarov", 
                page: "88-90", 
                date: "19.01.2026", 
                keywords: "Mahmudxo‘ja Behbudiy, jadidchilik, xalqaro dunyoqarash, G‘arb sivilizatsiyasi, modernizatsiya, matbuot, ta’lim islohoti.",
                file: "/1.pdf"},
            {id: 10, 
                slug: "abdulla-qodiriy-publististikasining-til-va-uslubiy-xususiyatlari",
                title: "ABDULLA QODIRIY PUBLISTISTIKASINING TIL VA USLUBIY XUSUSIYATLARI", 
                author: "Nazokatxon ISOQOVA", 
                page: "91-94", 
                date: "19.01.2026", 
                keywords: "Mahmudxo‘ja Behbudiy, jadidchilik, xalqaro dunyoqarash, G‘arb sivilizatsiyasi, modernizatsiya, matbuot, ta’lim islohoti.",
                file: "/1.pdf"},
            {id: 11, 
                slug: "sayid-rizo-alizoda-publitsistikasi",
                title: "SAYID RIZO ALIZODA PUBLITSISTIKASI", 
                author: "Dilorom JONIXONOVA", 
                page: "95-103", 
                date: "19.01.2026", 
                keywords: "Mahmudxo‘ja Behbudiy, jadidchilik, xalqaro dunyoqarash, G‘arb sivilizatsiyasi, modernizatsiya, matbuot, ta’lim islohoti.",
                file: "/1.pdf"},
            {id: 12, 
                slug: "fitratning-hind-sayyohining-qissasi-risolasida-ijtimoiy-masalalar",
                title: "FITRATNING “HIND SAYYOHINING QISSASI” RISOLASIDA IJTIMOIY MASALALAR", 
                author: "Robiya NURIDDINBEKOVA", 
                page: "104-06", 
                date: "19.01.2026", 
                keywords: "Mahmudxo‘ja Behbudiy, jadidchilik, xalqaro dunyoqarash, G‘arb sivilizatsiyasi, modernizatsiya, matbuot, ta’lim islohoti.",
                file: "/1.pdf"},
            {id: 13, 
                slug: "dabiy-til-meyorlarining-jadid-matbuoti-va-bugungi-ijtimoiy-tarmoqlardagi-ahamiyati",
                title: "DABIY TIL ME’YORLARINING JADID MATBUOTI VA BUGUNGI IJTIMOIY TARMOQLARDAGI AHAMIYATI", 
                author: "Gulzoda OLIMJANOVA", 
                page: "107-110", 
                date: "19.01.2026", 
                keywords: "Mahmudxo‘ja Behbudiy, jadidchilik, xalqaro dunyoqarash, G‘arb sivilizatsiyasi, modernizatsiya, matbuot, ta’lim islohoti.",
                file: "/1.pdf"},
            {id: 14, 
                slug: "abdurauf-fitrat-asarlarida-milliy-uygonish-goyalari",
                title: "ABDURAUF FITRAT ASARLARIDA MILLIY UYG‘ONISH G‘OYALARI", 
                author: "Mohira ERKINOVA", 
                page: "111-113", 
                date: "19.01.2026", 
                keywords: "Mahmudxo‘ja Behbudiy, jadidchilik, xalqaro dunyoqarash, G‘arb sivilizatsiyasi, modernizatsiya, matbuot, ta’lim islohoti.",
                file: "/1.pdf"},
            {id: 15, 
                slug: "siyosiy-lider-imijini-shakllantirishda-jadid-publitsistik-merosi-va-zamonaviy-mediastrategiyalari",
                title: "SIYOSIY LIDER IMIJINI SHAKLLANTIRISHDA JADID PUBLITSISTIK MEROSI VA ZAMONAVIY MEDIASTRATEGIYALARI", 
                author: "Munisaxon HASANOVA", 
                page: "113-116", 
                date: "19.01.2026", 
                keywords: "Mahmudxo‘ja Behbudiy, jadidchilik, xalqaro dunyoqarash, G‘arb sivilizatsiyasi, modernizatsiya, matbuot, ta’lim islohoti.",
                file: "/1.pdf"},
            {id: 16, 
                slug: "jadid-matbuotining-milliy-jurnalistikada-tutgan-orni-va-ahamiyati",
                title: "JADID MATBUOTINING MILLIY JURNALISTIKADA TUTGAN O‘RNI VA AHAMIYATI", 
                author: "Azizbek CHORIYEV", 
                page: "117-122", 
                date: "19.01.2026", 
                keywords: "Mahmudxo‘ja Behbudiy, jadidchilik, xalqaro dunyoqarash, G‘arb sivilizatsiyasi, modernizatsiya, matbuot, ta’lim islohoti.",
                file: "/1.pdf"},
            {id: 17, 
                slug: "jadid-matbuoti-va-milliy-jurnalistika-ozod-sharafiddinov-talqinida-adabiyot-yashasa-–-millat-yashar",
                title: "JADID MATBUOTI VA MILLIY JURNALISTIKA: OZOD SHARAFIDDINOV TALQINIDA “ADABIYOT YASHASA – MILLAT YASHAR”", 
                author: "Qodir MURTOZOYEV", 
                page: "123-127", 
                date: "19.01.2026", 
                keywords: "Mahmudxo‘ja Behbudiy, jadidchilik, xalqaro dunyoqarash, G‘arb sivilizatsiyasi, modernizatsiya, matbuot, ta’lim islohoti.",
                file: "/1.pdf"},
            {id: 18, 
                slug: "jadidlar-davrida-vaqtli-matbuot-marifat-milliy-uygonish-va-ijtimoiy-islohotlar-targibotida-gazeta-va-jurnallarning-orni",
                title: "JADIDLAR DAVRIDA VAQTLI MATBUOT: MA’RIFAT, MILLIY UYG‘ONISH VA IJTIMOIY ISLOHOTLAR TARG‘IBOTIDA GAZETA VA JURNALLARNING O‘RNI", 
                author: "Dilafruz YIGITALIYEVA", 
                page: "128-131", 
                date: "19.01.2026", 
                keywords: "Mahmudxo‘ja Behbudiy, jadidchilik, xalqaro dunyoqarash, G‘arb sivilizatsiyasi, modernizatsiya, matbuot, ta’lim islohoti.",
                file: "/1.pdf"},
            {id: 19, 
                slug: "fitrat-as-a-publicist-and-editor-his-role-in-the-development-of-jadid-journalism-and-national-consciousness",
                title: "FITRAT AS A PUBLICIST AND EDITOR - HIS ROLE IN THE DEVELOPMENT OF JADID JOURNALISM AND NATIONAL CONSCIOUSNESS", 
                author: "Jasmina CHORIYEVA", 
                page: "132-135", 
                date: "19.01.2026", 
                keywords: "Mahmudxo‘ja Behbudiy, jadidchilik, xalqaro dunyoqarash, G‘arb sivilizatsiyasi, modernizatsiya, matbuot, ta’lim islohoti.",
                file: "/1.pdf"},
            {id: 20, 
                slug: "jadid-matbuotining-milliy-jurnalistika-taraqqiyotidagi-orni",
                title: "JADID MATBUOTINING MILLIY JURNALISTIKA TARAQQIYOTIDAGI O‘RNI", 
                author: "Hojiakbar MAXAMADJANOV", 
                page: "136-143", 
                date: "19.01.2026", 
                keywords: "Mahmudxo‘ja Behbudiy, jadidchilik, xalqaro dunyoqarash, G‘arb sivilizatsiyasi, modernizatsiya, matbuot, ta’lim islohoti.",
                file: "/1.pdf"},
        ]
    },
    "3": {
        title: "ZAMONAVIY JURNALISTIKA TARAQQIYOTINING DOLZARB MASALALARI",
        articles: [
            {id: 1, 
                slug: "prikladnye-aspekty-politicheskoj-reklami",
                title: "ПРИКЛАДНЫЕ АСПЕКТЫ ПОЛИТИЧЕСКОЙ РЕКЛАМЫ НА ЭЛЕКТОРАЛЬНОЕ ПОВЕДЕНИЕ ГРАЖДАН ТАДЖИКИСТАНА: СОЦИАЛЬНЫЙ АНАЛИЗ", 
                author: "И.И.Хамидиён & Б.С.Мансурова", 
                page: "144-154", 
                date: "19.01.2026", 
                keywords: "Mahmudxo‘ja Behbudiy, jadidchilik, xalqaro dunyoqarash, G‘arb sivilizatsiyasi, modernizatsiya, matbuot, ta’lim islohoti.",
                file: "/1.pdf"},
            {id: 2, 
                slug: "modern-journalism-trends-new-formats-and-social-media-development-within-the-political-line-of-president-ilham-aliyev",
                title: `MODERN JOURNALISM: TRENDS, NEW FORMATS, AND SOCIAL MEDIA DEVELOPMENT WITHIN THE POLITICAL LINE OF PRESIDENT ILHAM ALIYEV`, 
                author: "Babayeva-Şükürova Fərahilə", 
                page: "155-157", 
                date: "19.01.2026", 
                keywords: "Mahmudxo‘ja Behbudiy, jadidchilik, xalqaro dunyoqarash, G‘arb sivilizatsiyasi, modernizatsiya, matbuot, ta’lim islohoti.",
                file: "/1.pdf"},
            {id: 3, 
                slug: "analiticheskie-zhanry-i-socialьnaya-zhurnalistika-kak-instrument-osmysleniya-i-obsuzhdeniya-problem-sfery-obrazovaniya-v-mestnoj-periodicheskoj-presse-tadzhikistana-issledovanie-na-primere-materialov-gazety-«hatlon»",
                title: "АНАЛИТИЧЕСКИЕ ЖАНРЫ И СОЦИАЛЬНАЯ ЖУРНАЛИСТИКА КАК ИНСТРУМЕНТ ОСМЫСЛЕНИЯ И ОБСУЖДЕНИЯ ПРОБЛЕМ СФЕРЫ ОБРАЗОВАНИЯ В МЕСТНОЙ ПЕРИОДИЧЕСКОЙ ПРЕССЕ ТАДЖИКИСТАНА (исследование на примере материалов газеты «Хатлон»)", 
                author: "Маъмурзода Носирджон Маъмур & Хайрзода Рамазон Ашурали", 
                page: "158-173", 
                date: "19.01.2026", 
                keywords: "Mahmudxo‘ja Behbudiy, jadidchilik, xalqaro dunyoqarash, G‘arb sivilizatsiyasi, modernizatsiya, matbuot, ta’lim islohoti.",
                file: "/1.pdf"},
            {id: 4, 
                slug: "media-kak-faktor-formirovaniya-obshestvennogo-immuniteta-k-radikalizmu",
                title: "МЕДИА КАК ФАКТОР ФОРМИРОВАНИЯ ОБЩЕСТВЕННОГО ИММУНИТЕТА К РАДИКАЛИЗМУ", 
                author: "Малика АХМЕДОВА", 
                page: "174-179", 
                date: "19.01.2026", 
                keywords: "Mahmudxo‘ja Behbudiy, jadidchilik, xalqaro dunyoqarash, G‘arb sivilizatsiyasi, modernizatsiya, matbuot, ta’lim islohoti.",
                file: "/1.pdf"},
            {id: 5, 
                slug: "baspa-isinde-redaktorliq-jumis-ham-tekst-sapasin-tamiyinlewdin-geypara-maseleleri",
                title: "BASPA ISINDE REDAKTORLIQ JUMÍS HÁM TEKST SAPASÍN TÁMIYINLEWDIŃ GEYPARA MÁSELELERI", 
                author: "Masharipova T.J. & Maratova S.M.", 
                page: "180-183", 
                date: "19.01.2026", 
                keywords: "Mahmudxo‘ja Behbudiy, jadidchilik, xalqaro dunyoqarash, G‘arb sivilizatsiyasi, modernizatsiya, matbuot, ta’lim islohoti.",
                file: "/1.pdf"},
            {id: 6, 
                slug: "journalism-and-newspaper-writing",
                title: "JOURNALISM AND NEWSPAPER WRITING", 
                author: "Kenan Novruzov", 
                page: "184-188", 
                date: "19.01.2026", 
                keywords: "Mahmudxo‘ja Behbudiy, jadidchilik, xalqaro dunyoqarash, G‘arb sivilizatsiyasi, modernizatsiya, matbuot, ta’lim islohoti.",
                file: "/1.pdf"},
            {id: 7, 
                slug: "boqiy-meros-charchashmalari-yoxud-saydi-umirov-publitsistikasida-jadidshunos-olimlar-ijodi-tahlili",
                title: "BOQIY MEROS CHARCHASHMALARI YOXUD SAYDI UMIROV PUBLITSISTIKASIDA JADIDSHUNOS OLIMLAR IJODI TAHLILI", 
                author: "Zulfiya FAYZULLAYEVA", 
                page: "189-192", 
                date: "19.01.2026", 
                keywords: "Mahmudxo‘ja Behbudiy, jadidchilik, xalqaro dunyoqarash, G‘arb sivilizatsiyasi, modernizatsiya, matbuot, ta’lim islohoti.",
                file: "/1.pdf"},
            {id: 8, 
                slug: "fijet-haqida-eshitganmisiz",
                title: "FIJET HAQIDA ESHITGANMISIZ?", 
                author: "Munira ISOMIDDINOVA", 
                page: "193-196", 
                date: "19.01.2026", 
                keywords: "Mahmudxo‘ja Behbudiy, jadidchilik, xalqaro dunyoqarash, G‘arb sivilizatsiyasi, modernizatsiya, matbuot, ta’lim islohoti.",
                file: "/1.pdf"},
            {id: 9, 
                slug: "transformaciya-zhurnalistiki-v-konvergentnoe-media",
                title: "ТРАНСФОРМАЦИЯ ЖУРНАЛИСТИКИ В КОНВЕРГЕНТНОЕ МЕДИА", 
                author: "Назокат ХАМРАКУЛОВА", 
                page: "197-206", 
                date: "19.01.2026", 
                keywords: "Mahmudxo‘ja Behbudiy, jadidchilik, xalqaro dunyoqarash, G‘arb sivilizatsiyasi, modernizatsiya, matbuot, ta’lim islohoti.",
                file: "/1.pdf"},
            {id: 10, 
                slug: "raqamli-muhitdagi-salbiy-tendensiyalar-clickbait-va-manipulyatsiya",
                title: "RAQAMLI MUHITDAGI SALBIY TENDENSIYALAR: CLICKBAIT VA MANIPULYATSIYA", 
                author: "Iroda MURODJONOVA", 
                page: "207-210", 
                date: "19.01.2026", 
                keywords: "Mahmudxo‘ja Behbudiy, jadidchilik, xalqaro dunyoqarash, G‘arb sivilizatsiyasi, modernizatsiya, matbuot, ta’lim islohoti.",
                file: "/1.pdf"},
            {id: 11, 
                slug: "suniy-intellekt-yordamida-ijtimoiy-tarmoqlarda-salbiy-sentimentni-aniqlash-mexanizmlari",
                title: "SUN’IY INTELLEKT YORDAMIDA IJTIMOIY TARMOQLARDA SALBIY SENTIMENTNI ANIQLASH MEXANIZMLARI", 
                author: "Gulmira SHUKUROVA", 
                page: "211-213", 
                date: "19.01.2026", 
                keywords: "Mahmudxo‘ja Behbudiy, jadidchilik, xalqaro dunyoqarash, G‘arb sivilizatsiyasi, modernizatsiya, matbuot, ta’lim islohoti.",
                file: "/1.pdf"},
            {id: 12, 
                slug: "destruktiv-tashkilotlar-millatlararo-totuvlik-masalalarini-mediada-yoritilishi",
                title: "DESTRUKTIV TASHKILOTLAR, MILLATLARARO TOTUVLIK MASALALARINI MEDIADA YORITILISHI", 
                author: "Dildora RIZAYEVA", 
                page: "214-218", 
                date: "19.01.2026", 
                keywords: "Mahmudxo‘ja Behbudiy, jadidchilik, xalqaro dunyoqarash, G‘arb sivilizatsiyasi, modernizatsiya, matbuot, ta’lim islohoti.",
                file: "/1.pdf"},
            {id: 13, 
                slug: "koreys-va-ozbek-tillarida-boglovchilarning-morfologik-va-sintaktik-orni",
                title: "KOREYS VA O‘ZBEK TILLARIDA BOG‘LOVCHILARNING MORFOLOGIK VA SINTAKTIK O‘RNI", 
                author: "Dilnoza BAXRANOVA & Jasmina RAFIQOVA", 
                page: "219-222", 
                date: "19.01.2026", 
                keywords: "Mahmudxo‘ja Behbudiy, jadidchilik, xalqaro dunyoqarash, G‘arb sivilizatsiyasi, modernizatsiya, matbuot, ta’lim islohoti.",
                file: "/1.pdf"},
            {id: 14, 
                slug: "zamonaviy-onlayn-oavda-ekologik-kontent-ishlab-chiqish-tendensiyalari-suv-muammolari-mavzusining-media-formatlar-orqali-talqini",
                title: "ZAMONAVIY ONLAYN OAVDA EKOLOGIK KONTENT ISHLAB CHIQISH TENDENSIYALARI: SUV MUAMMOLARI MAVZUSINING MEDIA FORMATLAR ORQALI TALQINI", 
                author: "Malika SABUROVA", 
                page: "223-229", 
                date: "19.01.2026", 
                keywords: "Mahmudxo‘ja Behbudiy, jadidchilik, xalqaro dunyoqarash, G‘arb sivilizatsiyasi, modernizatsiya, matbuot, ta’lim islohoti.",
                file: "/1.pdf"},
            {id: 15, 
                slug: "osoznanie-nakazaniya-i-vnutrennyaya-transformaciya-personazhej-v-romane-kon-dzhijona-«nashi-schastlivye-vremena»",
                title: "ОСОЗНАНИЕ НАКАЗАНИЯ И ВНУТРЕННЯЯ ТРАНСФОРМАЦИЯ ПЕРСОНАЖЕЙ В РОМАНЕ КОН ДЖИЙОНА «НАШИ СЧАСТЛИВЫЕ ВРЕМЕНА»", 
                author: "Ситора ТУРАКУЛОВА", 
                page: "230-235", 
                date: "19.01.2026", 
                keywords: "Mahmudxo‘ja Behbudiy, jadidchilik, xalqaro dunyoqarash, G‘arb sivilizatsiyasi, modernizatsiya, matbuot, ta’lim islohoti.",
                file: "/1.pdf"},
            {id: 16, 
                slug: "gibrid-til-tillar-aloqasi-va-madaniy-ozaro-tasir-mahsuli",
                title: "GIBRID TIL: TILLAR ALOQASI VA MADANIY O‘ZARO TA’SIR MAHSULI", 
                author: "Gulmira ESHQUVVATOVA & Zebo KARIMOVA", 
                page: "236-239", 
                date: "19.01.2026", 
                keywords: "Mahmudxo‘ja Behbudiy, jadidchilik, xalqaro dunyoqarash, G‘arb sivilizatsiyasi, modernizatsiya, matbuot, ta’lim islohoti.",
                file: "/1.pdf"},
            {id: 17, 
                slug: "real-voqealarga-asoslangan-seriallar-televizion-mahsulot-sifatida",
                title: "REAL VOQEALARGA ASOSLANGAN SERIALLAR TELEVIZION MAHSULOT SIFATIDA", 
                author: "Xurshidabonu NAZAROVA", 
                page: "240-242", 
                date: "19.01.2026", 
                keywords: "Mahmudxo‘ja Behbudiy, jadidchilik, xalqaro dunyoqarash, G‘arb sivilizatsiyasi, modernizatsiya, matbuot, ta’lim islohoti.",
                file: "/1.pdf"},
            {id: 18, 
                slug: "sformirovanie-fotopublicistiki-v-pervyh-karakalpakskih-gazetah",
                title: "СФОРМИРОВАНИЕ ФОТОПУБЛИЦИСТИКИ В ПЕРВЫХ КАРАКАЛПАКСКИХ ГАЗЕТАХ", 
                author: "Халима ХАЛИЛАЕВА", 
                page: "243-248", 
                date: "19.01.2026", 
                keywords: "Mahmudxo‘ja Behbudiy, jadidchilik, xalqaro dunyoqarash, G‘arb sivilizatsiyasi, modernizatsiya, matbuot, ta’lim islohoti.",
                file: "/1.pdf"},
            {id: 19, 
                slug: "vliyanie-socialьnyh-media-na-sovremennuyu-zhurnalistiku-v-usloviyah-cifrovizacii-mediaprostranstva",
                title: "ВЛИЯНИЕ СОЦИАЛЬНЫХ МЕДИА НА СОВРЕМЕННУЮ ЖУРНАЛИСТИКУ В УСЛОВИЯХ ЦИФРОВИЗАЦИИ МЕДИАПРОСТРАНСТВА", 
                author: "Дурдана ПЕРДЕБАЕВА", 
                page: "249-253", 
                date: "19.01.2026", 
                keywords: "Mahmudxo‘ja Behbudiy, jadidchilik, xalqaro dunyoqarash, G‘arb sivilizatsiyasi, modernizatsiya, matbuot, ta’lim islohoti.",
                file: "/1.pdf"},
            {id: 20, 
                slug: "internet-matnlarida-yangi-inovatsion-iboralarning-stilistik-xususiyatlari",
                title: "INTERNET MАTNLАRIDА YANGI INOVATSION IBORALARNING STILISTIK XUSUSIYАTLАRI", 
                author: "Gulmira ESHQUVVATOVA", 
                page: "254-262", 
                date: "19.01.2026", 
                keywords: "Mahmudxo‘ja Behbudiy, jadidchilik, xalqaro dunyoqarash, G‘arb sivilizatsiyasi, modernizatsiya, matbuot, ta’lim islohoti.",
                file: "/1.pdf"},
            {id: 21, 
                slug: "global-mediada-yechimlar-jurnalistikasining-vujudga-kelishi-va-taraqqiyoti",
                title: "GLOBAL MEDIADA YECHIMLAR JURNALISTIKASINING VUJUDGA KELISHI VA TARAQQIYOTI", 
                author: "Nodira SULEYMONOVA", 
                page: "263-268", 
                date: "19.01.2026", 
                keywords: "Mahmudxo‘ja Behbudiy, jadidchilik, xalqaro dunyoqarash, G‘arb sivilizatsiyasi, modernizatsiya, matbuot, ta’lim islohoti.",
                file: "/1.pdf"},
            {id: 22, 
                slug: "mediahajp-v-epohu-cifrovyh-platform-algoritmy-vnimaniya-i-transformaciya-sovremennoj-zhurnalistiki",
                title: "МЕДИАХАЙП В ЭПОХУ ЦИФРОВЫХ ПЛАТФОРМ: АЛГОРИТМЫ ВНИМАНИЯ И ТРАНСФОРМАЦИЯ СОВРЕМЕННОЙ ЖУРНАЛИСТИКИ", 
                author: "Зарифа ТАЖИЕВА", 
                page: "269-277", 
                date: "19.01.2026", 
                keywords: "Mahmudxo‘ja Behbudiy, jadidchilik, xalqaro dunyoqarash, G‘arb sivilizatsiyasi, modernizatsiya, matbuot, ta’lim islohoti.",
                file: "/1.pdf"},
            {id: 23, 
                slug: "jadid-matbuotida-xotinqizlar-ijtimoiy-faolligi-masalasining-yoritilishi",
                title: "JADID MATBUOTIDA XOTINQIZLAR IJTIMOIY FAOLLIGI MASALASINING YORITILISHI", 
                author: "Sayyora KADIROVA", 
                page: "278-280", 
                date: "19.01.2026", 
                keywords: "Mahmudxo‘ja Behbudiy, jadidchilik, xalqaro dunyoqarash, G‘arb sivilizatsiyasi, modernizatsiya, matbuot, ta’lim islohoti.",
                file: "/1.pdf"},
            {id: 24, 
                slug: "development-trends-in-modern-journalism-perception-of-the-quality-of-news-content-in-the-mass-media",
                title: "DEVELOPMENT TRENDS IN MODERN JOURNALISM PERCEPTION OF THE QUALITY OF NEWS CONTENT IN THE MASS MEDIA", 
                author: "Zulkhumor SOLIEVA", 
                page: "281-284", 
                date: "19.01.2026", 
                keywords: "Mahmudxo‘ja Behbudiy, jadidchilik, xalqaro dunyoqarash, G‘arb sivilizatsiyasi, modernizatsiya, matbuot, ta’lim islohoti.",
                file: "/1.pdf"},
            {id: 25, 
                slug: "jurnalistika-taraqqiyot-tendensiyalari",
                title: "JURNALISTIKA TARAQQIYOT TENDENSIYALARI", 
                author: "Muhlisa KAMOLOVA", 
                page: "285-287", 
                date: "19.01.2026", 
                keywords: "Mahmudxo‘ja Behbudiy, jadidchilik, xalqaro dunyoqarash, G‘arb sivilizatsiyasi, modernizatsiya, matbuot, ta’lim islohoti.",
                file: "/1.pdf"},
            {id: 26, 
                slug: "ijtimoiy-tarmoqlarda-bolalarga-oid-kontentlarda-etik-meyorlarga-amal-qilish-masalasi",
                title: "IJTIMOIY TARMOQLARDA BOLALARGA OID KONTENTLARDA ETIK MEYORLARGA AMAL QILISH MASALASI", 
                author: "Orzugul KARIMOVA", 
                page: "288-291", 
                date: "19.01.2026", 
                keywords: "Mahmudxo‘ja Behbudiy, jadidchilik, xalqaro dunyoqarash, G‘arb sivilizatsiyasi, modernizatsiya, matbuot, ta’lim islohoti.",
                file: "/1.pdf"},
            {id: 27, 
                slug: "mahmudxoja-behbudiy-maqolalarida-ijtimoiy-siyosiy-muammolarning-aks-etishi",
                title: "BOLALAR UCHUN MO‘LJALLANGAN INTERNET LOYIHALARDA AUDITORIYA BILAN ISHLASH STRATEGIYALARI (YOUTUBE KANALLAR MISOLIDA)", 
                author: "Gulnoza BEGIMQULOVA", 
                page: "292-293", 
                date: "19.01.2026", 
                keywords: "Mahmudxo‘ja Behbudiy, jadidchilik, xalqaro dunyoqarash, G‘arb sivilizatsiyasi, modernizatsiya, matbuot, ta’lim islohoti.",
                file: "/1.pdf"},
            {id: 28, 
                slug: "ayollar-huquqlarining-dolzarbligi-hamda-jadidlarning-gender-tengligiga-oid-qarashlari",
                title: "AYOLLAR HUQUQLARINING DOLZARBLIGI HAMDA JADIDLARNING GENDER TENGLIGIGA OID QARASHLARI", 
                author: "Azizjon RASULOV & Mansurova Nigora", 
                page: "294-297", 
                date: "19.01.2026", 
                keywords: "Mahmudxo‘ja Behbudiy, jadidchilik, xalqaro dunyoqarash, G‘arb sivilizatsiyasi, modernizatsiya, matbuot, ta’lim islohoti.",
                file: "/1.pdf"},
            {id: 29,
                slug: "behbudiyning-marifatparvarlik-faoliyati",
                title: "BEHBUDIYNING MA`RIFATPARVARLIK FAOLIYATI", 
                author: "Muqaddas QURBONOVA", 
                page: "298-301", 
                date: "19.01.2026", 
                doi: "https://doi.org/10.5281/zenodo.19035345",
                abstract: ``,
                file: "/57.pdf", 
                keywords: "Ayollar huquqlari, gender tengligi, jadidchilik harakati, ayollar ta’limi, Mahmudxo‘ja Behbudiy, Abdulla Avloniy, ijtimoiy tenglik, Abdurauf Fitrat."},
            {id: 30,
                slug: "jadid-matbuotida-ijodiy-boshqaruvning-oziga-xosligi",
                title: "JADID MATBUOTIDA IJODIY BOSHQARUVNING O‘ZIGA XOSLIGI", 
                author: "Maftuna ABDUKARIMOVA", 
                page: "302-308", 
                date: "19.01.2026", 
                doi: "https://doi.org/10.5281/zenodo.19035360",
                abstract: ``,
                file: "/58.pdf", 
                keywords: "Ayollar huquqlari, gender tengligi, jadidchilik harakati, ayollar ta’limi, Mahmudxo‘ja Behbudiy, Abdulla Avloniy, ijtimoiy tenglik, Abdurauf Fitrat."},
        ]
    }
}

export const dynamicParams = false;

export default async function Variations({ params }){

    const { id } = await params;
    const variation = variations[id]

    return(
        <>
            <ArticleList variation={variation} />
        </>
    )
}

export async function generateStaticParams() {
  return Object.keys(variations).map(id => ({ id }));
}
